'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useAuthStore } from '@/lib/store/auth-store';
import { useChatStore } from '@/lib/store/chat-store';
import type { GeneratedProjectVersion } from '@/types';
import Header from '@/components/layout/Header';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Plus, Send, Loader2, MessageSquare, History, ChevronLeft, ChevronRight, Code, Monitor } from 'lucide-react';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

export default function ChatPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { user, initialize, initialized } = useAuthStore();
  const conversations = useChatStore((state) => state.conversations);
  const currentConversation = useChatStore((state) => state.currentConversation);
  const messages = useChatStore((state) => state.messages);
  const loading = useChatStore((state) => state.loading);
  const fetchConversations = useChatStore((state) => state.fetchConversations);
  const createConversation = useChatStore((state) => state.createConversation);
  const setCurrentConversation = useChatStore((state) => state.setCurrentConversation);
  const sendMessage = useChatStore((state) => state.sendMessage);
  const subscribeToMessages = useChatStore((state) => state.subscribeToMessages);
  const generateProject = useChatStore((state) => state.generateProject);
  const fetchProjectVersions = useChatStore((state) => state.fetchProjectVersions);
  const saveProjectVersion = useChatStore((state) => state.saveProjectVersion);
  const updateProjectVersion = useChatStore((state) => state.updateProjectVersion);
  const projectVersionsMap = useChatStore((state) => state.projectVersions);
  const conversationId = currentConversation?.id ?? null;

  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [newConversationTitle, setNewConversationTitle] = useState('');
  const [messageInput, setMessageInput] = useState('');
  const [isSending, setIsSending] = useState(false);
  const [isRestoring, setIsRestoring] = useState(false);
  const [generatedProject, setGeneratedProject] = useState<GeneratedProjectVersion | null>(null);
  const [activeVersionId, setActiveVersionId] = useState<string | null>(null);
  const [selectedFileIndex, setSelectedFileIndex] = useState(0);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(true); // 默认折叠
  const [viewMode, setViewMode] = useState<'preview' | 'code'>('preview'); // 视图切换
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!initialized) {
      initialize();
    }
  }, [initialized, initialize]);

  useEffect(() => {
    if (initialized && !user) {
      navigate('/login');
    }
  }, [user, initialized, navigate]);

  useEffect(() => {
    if (user) {
      fetchConversations();
    }
  }, [user, fetchConversations]);

  useEffect(() => {
    if (currentConversation) {
      const unsubscribe = subscribeToMessages(currentConversation.id);
      return () => unsubscribe();
    }
  }, [currentConversation, subscribeToMessages]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  useEffect(() => {
    if (conversationId) {
      fetchProjectVersions(conversationId).catch((error) =>
        console.error('Failed to fetch project versions', error),
      );
    }
  }, [conversationId, fetchProjectVersions]);

  // 检测从首页跳转过来的情况，自动调用大模型 API
  useEffect(() => {
    const prompt = searchParams.get('prompt');
    
    if (prompt && currentConversation && !hasAutoGenerated) {
      setHasAutoGenerated(true);
      
      // 自动调用大模型 API 生成项目
      const autoGenerateProject = async () => {
        setIsSending(true);
        try {
          toast.info('正在生成项目，请稍候...');
          const version = await generateProject(prompt);
          setGeneratedProject(version);
          setActiveVersionId(version.id);
          setSelectedFileIndex(0);

          if (version.summary) {
            await sendMessage(version.summary, 'assistant');
          }
          
          toast.success('项目生成成功！');
        } catch (error) {
          const message = error instanceof Error ? error.message : 'Failed to generate project';
          toast.error(message);
          console.error('Auto generate project error:', error);
        } finally {
          setIsSending(false);
        }
      };

      autoGenerateProject();
    }
  }, [searchParams, currentConversation, hasAutoGenerated, generateProject, sendMessage]);

  const versions = useMemo(() => {
    if (!conversationId) return [];
    return projectVersionsMap[conversationId] ?? [];
  }, [conversationId, projectVersionsMap]);

  useEffect(() => {
    if (!conversationId) {
      setGeneratedProject(null);
      setActiveVersionId(null);
      setSelectedFileIndex(0);
      return;
    }

    if (versions.length === 0) {
      setGeneratedProject(null);
      setActiveVersionId(null);
      setSelectedFileIndex(0);
      return;
    }

    const desiredVersion =
      (activeVersionId && versions.find((version) => version.id === activeVersionId)) || versions[0];

    if (generatedProject?.id !== desiredVersion.id) {
      setGeneratedProject(desiredVersion);
      setSelectedFileIndex(0);
    }

    if (activeVersionId !== desiredVersion.id) {
      setActiveVersionId(desiredVersion.id);
    }
  }, [conversationId, versions, activeVersionId, generatedProject?.id]);

  const handleCreateConversation = async () => {
    if (!newConversationTitle.trim()) {
      toast.error('Please enter a conversation title');
      return;
    }

    try {
      const conversation = await createConversation(newConversationTitle);
      toast.success('Conversation created');
      setIsCreateDialogOpen(false);
      setNewConversationTitle('');
      setCurrentConversation(conversation);
      setGeneratedProject(null);
    } catch (error) {
      toast.error('Failed to create conversation');
      console.error(error);
    }
  };

  const handleSendMessage = async () => {
    if (!messageInput.trim() || !currentConversation) return;

    setIsSending(true);
    const prompt = messageInput.trim();
    try {
      await sendMessage(prompt);
      setMessageInput('');

      const version = await generateProject(prompt);
      setGeneratedProject(version);
      setActiveVersionId(version.id);
      setSelectedFileIndex(0);

      if (version.summary) {
        await sendMessage(version.summary, 'assistant');
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to generate project';
      toast.error(message);
      console.error(error);
    } finally {
      setIsSending(false);
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const previewDocument = useMemo(() => {
    if (!generatedProject) return null;

    const htmlFile = generatedProject.files.find((file) => file.name.toLowerCase().endsWith('.html'));
    if (!htmlFile) return null;

    const css = generatedProject.files
      .filter((file) => file.name.toLowerCase().endsWith('.css'))
      .map((file) => `<style>${file.content}</style>`)
      .join('\n');

    const scripts = generatedProject.files
      .filter((file) => file.name.toLowerCase().endsWith('.js') || file.name.toLowerCase().endsWith('.ts'))
      .map((file) => `<script type="module">${file.content}</script>`)
      .join('\n');

    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
${css}
</head>
<body>
${htmlFile.content}
${scripts}
</body>
</html>`;
  }, [generatedProject]);

  if (!initialized || !user) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  const selectedFile = generatedProject?.files[selectedFileIndex];

  const handleRestoreVersion = async (version: GeneratedProjectVersion) => {
    if (!currentConversation) return;

    setIsRestoring(true);
    try {
      const updated = await updateProjectVersion(version.id, currentConversation.id, {
        summary: version.summary,
        files: version.files,
      });

      setActiveVersionId(updated.id);
      toast.success('Version restored');
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to restore version';
      toast.error(message);
      console.error(error);
    } finally {
      setIsRestoring(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50 flex flex-col">
      <Header />

      <div className="flex-1 container mx-auto px-4 py-6 flex gap-4">
        {/* Conversations Sidebar - 可折叠 */}
        <Card 
          className={cn(
            "flex flex-col transition-all duration-300",
            sidebarCollapsed ? "w-12" : "w-64 md:w-72"
          )}
        >
          <div className="p-4 border-b flex items-center justify-between">
            {!sidebarCollapsed && <h2 className="font-semibold">Conversations</h2>}
            <Button 
              size="sm" 
              variant="ghost"
              onClick={() => setSidebarCollapsed(!sidebarCollapsed)}
              className={cn(sidebarCollapsed && "mx-auto")}
            >
              {sidebarCollapsed ? <ChevronRight className="h-4 w-4" /> : <ChevronLeft className="h-4 w-4" />}
            </Button>
          </div>

          {!sidebarCollapsed && (
            <>
              <div className="p-4 border-b">
                <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
                  <DialogTrigger asChild>
                    <Button size="sm" variant="outline" className="w-full gap-2">
                      <Plus className="h-4 w-4" />
                      New Chat
                    </Button>
                  </DialogTrigger>
                  <DialogContent>
                    <DialogHeader>
                      <DialogTitle>New Conversation</DialogTitle>
                      <DialogDescription>Start a new conversation</DialogDescription>
                    </DialogHeader>
                    <div className="space-y-4 py-4">
                      <div className="space-y-2">
                        <Label htmlFor="title">Title</Label>
                        <Input
                          id="title"
                          placeholder="Conversation title"
                          value={newConversationTitle}
                          onChange={(e) => setNewConversationTitle(e.target.value)}
                        />
                      </div>
                    </div>
                    <DialogFooter>
                      <Button variant="outline" onClick={() => setIsCreateDialogOpen(false)}>
                        Cancel
                      </Button>
                      <Button onClick={handleCreateConversation}>Create</Button>
                    </DialogFooter>
                  </DialogContent>
                </Dialog>
              </div>

              <ScrollArea className="flex-1">
                {loading ? (
                  <div className="flex items-center justify-center py-8">
                    <Loader2 className="h-6 w-6 animate-spin text-primary" />
                  </div>
                ) : conversations.length === 0 ? (
                  <div className="p-4 text-center text-sm text-muted-foreground">No conversations yet</div>
                ) : (
                  <div className="p-2 space-y-1">
                    {conversations.map((conv) => (
                      <button
                        key={conv.id}
                        onClick={() => setCurrentConversation(conv)}
                        className={cn(
                          'w-full text-left p-3 rounded-lg hover:bg-accent transition-colors',
                          currentConversation?.id === conv.id && 'bg-accent',
                        )}
                      >
                        <div className="font-medium truncate">{conv.title}</div>
                        <div className="text-xs text-muted-foreground">
                          {new Date(conv.updated_at).toLocaleDateString()}
                        </div>
                      </button>
                    ))}
                  </div>
                )}
              </ScrollArea>
            </>
          )}
        </Card>

        <div className="flex flex-1 gap-4">
          {/* Chat Area - 缩小宽度 */}
          <Card className="flex-[3] flex flex-col">
            {currentConversation ? (
              <>
                <div className="p-4 border-b">
                  <h2 className="font-semibold">{currentConversation.title}</h2>
                </div>

                <ScrollArea className="flex-1 p-4">
                  {messages.length === 0 && !isSending ? (
                    <div className="flex flex-col items-center justify-center h-full text-center">
                      <MessageSquare className="h-12 w-12 text-muted-foreground mb-4" />
                      <p className="text-muted-foreground">No messages yet. Start the conversation!</p>
                    </div>
                  ) : (
                    <div className="space-y-4">
                      {messages.map((message) => (
                        <div
                          key={message.id}
                          className={cn('flex', message.role === 'user' ? 'justify-end' : 'justify-start')}
                        >
                          <div
                            className={cn(
                              'max-w-[70%] rounded-lg p-3',
                              message.role === 'user'
                                ? 'bg-primary text-primary-foreground'
                                : 'bg-muted',
                            )}
                          >
                            <p className="text-sm whitespace-pre-wrap">{message.content}</p>
                            <p className="text-xs opacity-70 mt-1">
                              {new Date(message.created_at).toLocaleTimeString()}
                            </p>
                          </div>
                        </div>
                      ))}
                      {/* Generating Loading Placeholder */}
                      {isSending && (
                        <div className="flex justify-start">
                          <div className="max-w-[70%] rounded-lg p-3 bg-muted">
                            <div className="flex items-center gap-2">
                              <Loader2 className="h-4 w-4 animate-spin text-primary" />
                              <p className="text-sm text-muted-foreground">Generating...</p>
                            </div>
                          </div>
                        </div>
                      )}
                      <div ref={messagesEndRef} />
                    </div>
                  )}
                </ScrollArea>

                <div className="p-4 border-t">
                  <div className="flex gap-2">
                    <Input
                      placeholder="Describe the project you want..."
                      value={messageInput}
                      onChange={(e) => setMessageInput(e.target.value)}
                      onKeyPress={handleKeyPress}
                      disabled={isSending}
                    />
                    <Button onClick={handleSendMessage} disabled={isSending || !messageInput.trim()} size="icon">
                      {isSending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
                    </Button>
                  </div>
                </div>
              </>
            ) : (
              <div className="flex-1 flex items-center justify-center">
                <div className="text-center">
                  <MessageSquare className="h-16 w-16 text-muted-foreground mx-auto mb-4" />
                  <h3 className="text-lg font-semibold mb-2">No conversation selected</h3>
                  <p className="text-sm text-muted-foreground mb-4">
                    Select a conversation or create a new one to start chatting
                  </p>
                  <Button onClick={() => setIsCreateDialogOpen(true)} className="gap-2">
                    <Plus className="h-4 w-4" />
                    New Conversation
                  </Button>
                </div>
              </div>
            )}
          </Card>

          {/* Preview Area - 增大宽度 */}
          <Card className="flex-[5] flex flex-col overflow-hidden">
            <div className="border-b p-4 flex items-center justify-between">
              <div>
                <h2 className="font-semibold text-slate-800">Project Preview</h2>
                <p className="text-xs text-muted-foreground">
                  View the AI generated summary, live preview, and source code files.
                </p>
              </div>
              {versions.length > 0 && (
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <History className="h-4 w-4" />
                  <span>{versions.length} versions</span>
                </div>
              )}
            </div>
            {generatedProject ? (
              <div className="flex flex-1 flex-col overflow-hidden">
                <div className="border-b p-4">
                  <h3 className="text-sm font-semibold text-slate-700">Summary</h3>
                  <p className="mt-2 text-sm text-slate-600 whitespace-pre-wrap">
                    {generatedProject.summary || 'The assistant did not provide a summary.'}
                  </p>
                </div>
                <div className="border-b px-4 py-3">
                  {versions.length > 0 ? (
                    <ScrollArea className="max-h-32 pr-2">
                      <div className="space-y-2">
                        {versions.map((version, index) => {
                          const versionNumber = versions.length - index;
                          const isActive = version.id === activeVersionId;
                          const createdAt = new Date(version.created_at).toLocaleString();
                          return (
                            <div key={version.id} className="flex items-center gap-2">
                              <Button
                                variant={isActive ? 'default' : 'ghost'}
                                size="sm"
                                className="flex-1 justify-start"
                                onClick={() => setActiveVersionId(version.id)}
                              >
                                <span className="font-medium">v{versionNumber}</span>
                                <span className="ml-2 text-xs opacity-60">{createdAt}</span>
                              </Button>
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => handleRestoreVersion(version)}
                                disabled={isRestoring}
                              >
                                Restore
                              </Button>
                            </div>
                          );
                        })}
                      </div>
                    </ScrollArea>
                  ) : (
                    <p className="text-xs text-muted-foreground">No versions yet.</p>
                  )}
                </div>
                
                {/* 视图切换栏 */}
                <div className="border-b px-4 py-2 flex items-center gap-2 bg-slate-50">
                  <Button
                    variant={viewMode === 'preview' ? 'default' : 'ghost'}
                    size="sm"
                    onClick={() => setViewMode('preview')}
                    className="gap-2"
                  >
                    <Monitor className="h-4 w-4" />
                    Preview
                  </Button>
                  <Button
                    variant={viewMode === 'code' ? 'default' : 'ghost'}
                    size="sm"
                    onClick={() => setViewMode('code')}
                    className="gap-2"
                  >
                    <Code className="h-4 w-4" />
                    Code
                  </Button>
                </div>

                <div className="flex-1 overflow-hidden flex flex-col">
                  {viewMode === 'preview' ? (
                    // 预览模式
                    previewDocument ? (
                      <iframe
                        key={currentConversation?.id}
                        title="Project Preview"
                        srcDoc={previewDocument}
                        className="flex-1 w-full"
                        sandbox="allow-scripts allow-same-origin"
                      />
                    ) : (
                      <div className="flex flex-1 items-center justify-center text-sm text-muted-foreground">
                        No HTML preview available for this project.
                      </div>
                    )
                  ) : (
                    // 代码模式
                    <div className="flex flex-col flex-1 overflow-hidden">
                      <div className="flex flex-wrap gap-2 border-b px-4 py-3 bg-slate-50">
                        {generatedProject.files.map((file, index) => (
                          <Button
                            key={`${file.name}-${index}`}
                            variant={selectedFileIndex === index ? 'default' : 'outline'}
                            size="sm"
                            onClick={() => setSelectedFileIndex(index)}
                          >
                            {file.name}
                          </Button>
                        ))}
                      </div>
                      <ScrollArea className="flex-1 p-4">
                        {selectedFile ? (
                          <pre className="whitespace-pre-wrap break-words rounded-lg bg-slate-900/95 p-4 font-mono text-xs text-white">
                            {selectedFile.content}
                          </pre>
                        ) : (
                          <p className="text-sm text-muted-foreground">Select a file to inspect the generated code.</p>
                        )}
                      </ScrollArea>
                    </div>
                  )}
                </div>
              </div>
            ) : isSending ? (
              <div className="flex flex-1 items-center justify-center p-6">
                <div className="text-center">
                  <Loader2 className="h-12 w-12 animate-spin text-primary mx-auto mb-4" />
                  <p className="text-sm font-medium text-slate-700">Generating project...</p>
                  <p className="text-xs text-muted-foreground mt-2">This may take a few moments</p>
                </div>
              </div>
            ) : (
              <div className="flex flex-1 items-center justify-center p-6 text-sm text-muted-foreground">
                Generate a project by describing it in the chat input. The summary and code will appear here.
              </div>
            )}
          </Card>
        </div>
      </div>
    </div>
  );
}